# Site
name: "India Shares Investment"
title: "Indian Investments and Business Guide"
description: "Insightful news and analysis that helps investors make crucial decisions. Providing headlines on investment strategies, investing ideas and market trends."
meta_description: "Insightful news and analysis that helps investors make crucial decisions. Providing headlines on investment strategies, investing ideas and Indian market trends."
logo: 'assets/images/india_shares_investment_blog_logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'info@indiasharesinvestment.com'
google_analytics: ''
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Ambedkar Roy
    display_name: Ambedkar Roy
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: info@indiasharesinvestment.co
    web: indiasharesinvestment.com
    twitter: https://twitter.com/indiasharesinvestment
    description: ""
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
